export const pausePanelImg = [
  {
    type: "picture",
    name: "pause",
    image: "images/level/panels/pause_panel.png",
    x: 569,
    y: 300,
    width: 462,
    height: 600,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
];
export const pausePanelBtn = [
  {
    type: "button",
    name: "Продолжить",
    image: "images/level/panels/pauseBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 674,
    y: 345,
    width: 245,
    height: 70,
    sx: 0,
    sy: 0,
    swidth: 168,
    sheight: 48
  },
  {
    type: "button",
    name: "Главное Меню",
    image: "images/level/panels/pauseBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 674,
    y: 455,
    width: 245,
    height: 70,
    sx: 0,
    sy: 0,
    swidth: 168,
    sheight: 48
  },
  {
    type: "button",
    name: "Перезапустить",
    image: "images/level/panels/pauseBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 674,
    y: 565,
    width: 245,
    height: 70,
    sx: 0,
    sy: 0,
    swidth: 168,
    sheight: 48
  },
  {
    type: "button",
    name: "Карта",
    image: "images/level/panels/pauseBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 674,
    y: 675,
    width: 245,
    height: 70,
    sx: 0,
    sy: 0,
    swidth: 168,
    sheight: 48
  },
  {
    type: "button",
    name: "Настройки",
    image: "images/level/panels/pauseBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 674,
    y: 785,
    width: 245,
    height: 70,
    sx: 0,
    sy: 0,
    swidth: 168,
    sheight: 48
  },
];

export const pausePanelText = [
  {
    text: 'Продолжить',
    fontSize: '27px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 714,
    y: 385,
    animation: false,
  },
  {
    text: "Главное Меню",
    fontSize: '27px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 707,
    y: 495,
    animation: false,
  },
  {
    text: "Перезапустить",
    fontSize: '27px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 707,
    y: 605,
    animation: false,
  },
  {
    text: "Карта",
    fontSize: '27px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 762,
    y: 715,
    animation: false,
  },
  {
    text: "Настройки",
    fontSize: '27px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 734,
    y: 825,
    animation: false,
  },
];