const imgOne = [
  {
    type: "button",
    name: "egg",
    image: "images/level/initial/egg.png",
    x: 524,
    y: 488,
    width: 60,
    height: 64,
    sx: 0,
    sy: 0,
    swidth: 60,
    sheight: 64
  },
];

const textOne = [
  {
    name: "eggsCount",
    text: '4',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 534,
    animation: false,
  },
  {
    name: "levelEnd",
    text: '25',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 920,
    y: 534,
    animation: false,
  },
  {
    name: "goldEnd",
    text: '+75',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 1026,
    y: 630,
    animation: false,
  },
  {
    name: "goldTime",
    text: '01:00',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 842,
    y: 682,
    animation: false,
  },
  {
    name: "silverEnd",
    text: '+25',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1026,
    y: 766,
    animation: false,
  },
  {
    name: "silverTimer",
    text: '02:00',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 838,
    y: 816,
    animation: false,
  },
];

const imgTwo = [
  {
    type: "button",
    name: "chicken",
    image: "images/pets/chicken/death.png",
    x: 510,
    y: 552,
    width: 100,
    height: 100,
    sx: 0,
    sy: 0,
    swidth: 64,
    sheight: 64
  },
  {
    type: "button",
    name: "egg",
    image: "images/level/initial/egg.png",
    x: 524,
    y: 488,
    width: 60,
    height: 64,
    sx: 0,
    sy: 0,
    swidth: 60,
    sheight: 64
  },
];

const textTwo = [
  {
    name: "eggsCount",
    text: '6',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 534,
    animation: false,
  },
  {
    name: "chickenCount",
    text: '3',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 628,
    animation: false,
  },
  {
    name: "levelEnd",
    text: '40',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 920,
    y: 534,
    animation: false,
  },
  {
    name: "goldEnd",
    text: '+120',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 1008,
    y: 630,
    animation: false,
  },
  {
    name: "goldTime",
    text: '01:30',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 842,
    y: 682,
    animation: false,
  },
  {
    name: "silverEnd",
    text: '+40',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1026,
    y: 766,
    animation: false,
  },
  {
    name: "silverTimer",
    text: '02:40',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 838,
    y: 816,
    animation: false,
  },
];

const imgThree = [
  {
    type: "button",
    name: "chicken",
    image: "images/pets/chicken/death.png",
    x: 510,
    y: 552,
    width: 100,
    height: 100,
    sx: 0,
    sy: 0,
    swidth: 64,
    sheight: 64
  },
  {
    type: "button",
    name: "egg",
    image: "images/level/initial/egg.png",
    x: 524,
    y: 488,
    width: 60,
    height: 64,
    sx: 0,
    sy: 0,
    swidth: 60,
    sheight: 64
  },
  {
    type: "button",
    name: "flour",
    image: "images/level/initial/flour.png",
    x: 520,
    y: 656,
    width: 80,
    height: 96,
    sx: 0,
    sy: 0,
    swidth: 80,
    sheight: 96
  },
];

const textThree = [
  {
    name: "eggsCount",
    text: '6',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 534,
    animation: false,
  },
  {
    name: "chickenCount",
    text: '3',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 628,
    animation: false,
  },
  {
    name: "flourCount",
    text: '2',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 722,
    animation: false,
  },
  {
    name: "levelEnd",
    text: '50',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 920,
    y: 534,
    animation: false,
  },
  {
    name: "goldEnd",
    text: '+150',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 1008,
    y: 630,
    animation: false,
  },
  {
    name: "goldTime",
    text: '02:00',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 842,
    y: 682,
    animation: false,
  },
  {
    name: "silverEnd",
    text: '+50',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1026,
    y: 766,
    animation: false,
  },
  {
    name: "silverTimer",
    text: '03:00',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 838,
    y: 816,
    animation: false,
  },
];

const imgFour = [
  {
    type: "button",
    name: "chicken",
    image: "images/pets/chicken/death.png",
    x: 510,
    y: 552,
    width: 100,
    height: 100,
    sx: 0,
    sy: 0,
    swidth: 64,
    sheight: 64
  },
  {
    type: "button",
    name: "cake",
    image: "images/level/initial/cake.png",
    x: 516,
    y: 494,
    width: 80,
    height: 46,
    sx: 0,
    sy: 0,
    swidth: 104,
    sheight: 60
  },

];

const textFour = [
  {
    name: "cakeCount",
    text: '2',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 534,
    animation: false,
  },
  {
    name: "chickenCount",
    text: '2',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 656,
    y: 628,
    animation: false,
  },
  {
    name: "levelEnd",
    text: '60',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 920,
    y: 534,
    animation: false,
  },
  {
    name: "goldEnd",
    text: '+190',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 1008,
    y: 630,
    animation: false,
  },
  {
    name: "goldTime",
    text: '02:30',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 846,
    y: 682,
    animation: false,
  },
  {
    name: "silverEnd",
    text: '+60',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1026,
    y: 766,
    animation: false,
  },
  {
    name: "silverTimer",
    text: '04:00',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 846,
    y: 816,
    animation: false,
  },
];

const imgFive = [
  {
    type: "button",
    name: "egg",
    image: "images/level/initial/egg.png",
    x: 524,
    y: 488,
    width: 60,
    height: 64,
    sx: 0,
    sy: 0,
    swidth: 60,
    sheight: 64
  },
  {
    type: "button",
    name: "flour",
    image: "images/level/initial/flour.png",
    x: 518,
    y: 552,
    width: 80,
    height: 96,
    sx: 0,
    sy: 0,
    swidth: 80,
    sheight: 96
  },
  {
    type: "button",
    name: "cake",
    image: "images/level/initial/cake.png",
    x: 516,
    y: 688,
    width: 80,
    height: 46,
    sx: 0,
    sy: 0,
    swidth: 104,
    sheight: 60
  },
];

const textFive = [
  {
    name: "cakeCount",
    text: '10',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 650,
    y: 728,
    animation: false,
  },
  {
    name: "eggCount",
    text: '20',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 650,
    y: 534,
    animation: false,
  },
  {
    name: "flourCount",
    text: '5',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 660,
    y: 628,
    animation: false,
  },

  {
    name: "levelEnd",
    text: '75',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 920,
    y: 534,
    animation: false,
  },
  {
    name: "goldEnd",
    text: '+175',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 1008,
    y: 630,
    animation: false,
  },
  {
    name: "goldTime",
    text: '03:10',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: 'yellow',
    x: 846,
    y: 682,
    animation: false,
  },
  {
    name: "silverEnd",
    text: '+75',
    fontSize: '46px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1026,
    y: 766,
    animation: false,
  },
  {
    name: "silverTimer",
    text: '04:10',
    fontSize: '30px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 846,
    y: 816,
    animation: false,
  },
];


export const levelInitial = {
  '1': {
    img: imgOne,
    text: textOne,
  },
  '2': {
    img: imgTwo,
    text: textTwo,
  },
  '3': {
    img: imgThree,
    text: textThree,
  },
  '4': {
    img: imgFour,
    text: textFour,
  },
  '5': {
    img: imgFive,
    text: textFive
  }
};

