export const storagePanelImg = [
  {
    type: "picture",
    name: "depotBack",
    image: "images/level/builds/storage/deportBack.png",
    x: 0,
    y: 0,
    width: 1600,
    height: 1200,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
  {
    type: "picture",
    name: "coin",
    image: "images/level/builds/storage/coin.png",
    x: 1170,
    y: 990,
    width: 48,
    height: 48,
    sx: 0,
    sy: 0,
    swidth: 28,
    sheight: 28
  },
  {
    type: "picture",
    name: "car-1",
    image: "images/level/builds/storage/car-1.png",
    x: 1060,
    y: 505,
    width: 500,
    height: 450,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
];



export const storagePanelBtn = [
  {
    type: "button",
    name: "Ок",
    image: "images/level/panels/startBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 800,
    y: 1080,
    width: 200,
    height: 77,
    sx: 0,
    sy: 144,
    swidth: 128,
    sheight: 48
  },
  {
    type: "button",
    name: "Отмена",
    image: "images/level/panels/startBtn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 530,
    y: 1080,
    width: 200,
    height: 77,
    sx: 0,
    sy: 0,
    swidth: 128,
    sheight: 48
  },
];

export const icons = {
  'egg': {
    type: "picture",
    name: "egg",
    image: "images/level/builds/storage/egg.png",
    x: 60,
    y: 0,
    width: 65,
    height: 65,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
  "bear-1": {
    type: "picture",
    name: "bear-1",
    image: "images/level/builds/storage/bear-1.png",
    x: 60,
    y: 0,
    width: 65,
    height: 65,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
  'coin': {
    type: "picture",
    name: "coin",
    image: "images/level/builds/storage/coin.png",
    x: 300,
    y: 0,
    width: 40,
    height: 40,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
  'btn': {
    type: "button",
    name: "Ок",
    image: "images/level/builds/storage/btn.png",
    stepY: 48,
    stepX: 0,
    hover: 1,
    click: 2,
    x: 300,
    y: 0,
    width: 60,
    height: 43,
    sx: 0,
    sy: 0,
    swidth: 40,
    sheight: 28
  },
  'flour': {
    type: "picture",
    name: "flour",
    image: "images/level/builds/storage/flour.png",
    x: 60,
    y: 0,
    width: 65,
    height: 65,
    sx: 0,
    sy: 0,
    swidth: 0,
    sheight: 0
  },
};

export const storagePanelStaticText = [
  {
    text: 'Продукты',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 50,
    y: 190,
    animation: false,
  },
  {
    text: 'Цена',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 240,
    y: 190,
    animation: false,
  },
  {
    text: 'Отгрузить',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 360,
    y: 190,
    animation: false,
  },
  {
    text: 'Отгрузка товара',
    fontSize: '68px Vag_Rounded-Bold CY',
    color: '#fbead0',
    x: 560,
    y: 94,
    animation: false,
  },
  {
    text: 'Продукты',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 568,
    y: 190,
    animation: false,
  },
  {
    text: 'Цена',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 758,
    y: 190,
    animation: false,
  },
  {
    text: 'Отгрузить',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 878,
    y: 190,
    animation: false,
  },
  {
    text: 'Животные',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 1084,
    y: 190,
    animation: false,
  },
  {
    text: 'Цена',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 1280,
    y: 190,
    animation: false,
  },
  {
    text: 'Отгрузить',
    fontSize: '32px Vag_Rounded-Bold CY',
    color: '#eed940',
    x: 1400,
    y: 190,
    animation: false,
  },
];

export const storagePanelText = [

  {
    text: 'Ок',
    fontSize: '34px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 876,
    y: 1125,
    animation: false,
  },
  {
    text: 'Отмена',
    fontSize: '34px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 570,
    y: 1125,
    animation: false,
  },
  {
    text: '0',
    name: 'total',
    fontSize: '40px Vag_Rounded-Bold CY',
    color: '#fff',
    x: 1320,
    y: 1025,
    animation: false,
  },
];